# Generated by Django 5.2.8 on 2025-11-10 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galpao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('capacidade_aves', models.IntegerField(default=0)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Granja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(blank=True, max_length=150, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atuador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ventilador', 'Ventilador'), ('luz', 'Luz'), ('bomba_agua', 'Bomba de Água'), ('aquecedor', 'Aquecedor')], max_length=20)),
                ('estado', models.BooleanField(default=False)),
                ('galpao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atuadores', to='core.galpao')),
            ],
        ),
        migrations.AddField(
            model_name='galpao',
            name='granja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galpoes', to='core.granja'),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('temperatura', 'Temperatura'), ('umidade', 'Umidade'), ('gases', 'Gases'), ('luminosidade', 'Luminosidade'), ('outro', 'Outro')], max_length=20)),
                ('unidade', models.CharField(default='', max_length=10)),
                ('galpao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='core.galpao')),
            ],
        ),
        migrations.CreateModel(
            name='RegraAutomacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicao', models.CharField(choices=[('>', 'Maior que'), ('<', 'Menor que')], max_length=10)),
                ('valor_referencia', models.FloatField()),
                ('ativo', models.BooleanField(default=True)),
                ('atuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='core.atuador')),
                ('galpao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='core.galpao')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='core.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='core.sensor')),
            ],
        ),
    ]
